name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - databricks-cli=0.8.7
  - mlflow=2.13.0
  - hydra-core=1.0.6
  - protobuf=3.20.0
  - numpy=1.23.4
  - uvicorn=0.30.1
  - gunicorn=22.0.0
  - pip:
      - wandb==0.18.7
      - hydra-joblib-launcher==1.1.2

