name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.31.0
  - databricks-cli=0.18.0
  - pip=23.3.1
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - mlflow=2.8.1
  - pip:
      - wandb==0.20.1